const SUPER_ADMIN = 1;
const MANAGER = 2;
const GENERAL = 3;
const ACCOUNTING = 4;
const LEAD_MANAGEMENT = 5;

export const ROLES = {
  SUPER_ADMIN,
  MANAGER,
  GENERAL,
  ACCOUNTING,
  LEAD_MANAGEMENT,
};
const SUPER_ROLE = [SUPER_ADMIN, MANAGER];
const SUPER_ADMIN_ROLES = [SUPER_ADMIN];
const GENERAL_ROLE = [GENERAL];
const ALL_ROLE = [SUPER_ADMIN, MANAGER, GENERAL];
